name: Docker Image CI for GHCR
on:
  push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests
      - name: Login to GHCR
        run: |
          echo ${{ secrets.CI_TOKEN }} | docker login ghcr.io -u francesco-plt --password-stdin
      - name: Build and push the image
        run: |
          docker build . --tag ghcr.io/voxelite-ai/pinggy-server:latest
          docker push ghcr.io/voxelite-ai/pinggy-server:latest